# Generated by Django 5.1.2 on 2025-07-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='account_image',
            field=models.ImageField(null=True, upload_to='transactions/'),
        ),
    ]
